#User Scan Statistics and Settings
<<<<<<< HEAD
#Mon Apr 27 18:28:59 IST 2026
=======
#Thu Apr 23 12:42:24 IST 2026
>>>>>>> 056546b (some sound work)
darkTheme=false
hashAlgorithm=SHA-256
lastFolder=/home/tahaur/Desktop/dummy folder for scan
<<<<<<< HEAD
minSizeKB=1024
skipHidden=true
soundEnabled=true
soundVolume=100.0
totalGroups=322
totalSaved=1116112989
totalScanned=790
=======
soundEnabled=true
soundVolume=1.0
totalGroups=96
totalSaved=333207724
totalScanned=199
>>>>>>> 056546b (some sound work)
