#User Scan Statistics and Settings
#Sun May 03 23:44:42 IST 2026
=\=\=\=\=\=\=
<<<<<<<=HEAD
>>>>>>>=056546b (some sound work)
darkTheme=false
hashAlgorithm=SHA-256
lastFolder=/home/tahaur/Desktop/dummy folder for scan
minSizeKB=1024
skipHidden=true
soundEnabled=true
soundVolume=1.0
totalGroups=2400
totalSaved=4884774521
totalScanned=3765
